import { Product } from './product.model';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'gongura-pickle',
    name: 'Gongura Pickle',
    category: 'Pickles',
    shortDescription: 'Tangy sorrel leaves combined with traditional Andhra spices for an unmatched flavor burst.',
    description: 'A staple in every Telugu household, our Gongura pickle is made from fresh, hand-picked sorrel leaves (Gongura). It is slowly simmered and infused with cold-pressed sesame oil, mustard seeds, fenugreek, and a high-heat chilli blend. The result is a perfect harmony of sour, spicy, and salty flavors that pairs wonderfully with hot rice and a spoonful of ghee.',
    spiceLevel: 'Hot',
    bestWith: ['Hot Rice + Ghee', 'Pappu (Lentil Dal)', 'Dosa', 'Idly'],
    ingredients: ['Fresh Sorrel Leaves (Gongura)', 'Cold-pressed Sesame Oil', 'Chilli Powder', 'Garlic', 'Salt', 'Mustard Seeds', 'Fenugreek Seeds', 'Turmeric'],
    storageInstructions: 'Store in dry place. Always use a dry spoon. Keep the jar tightly sealed.',
    shelfLife: '6 Months',
    allergenWarning: 'Contains mustard and garlic. Prepared in a facility handling sesame and nuts.',
    imagePath: 'img/gongura_pickle_packaging.jpg',
    secondaryImagePath: 'img/Gemini_Generated_Image_ (2).png',
    availabilityStatus: 'Limited Batch'
  },
  {
    id: 'mango-pickle',
    name: 'Mango Pickle',
    category: 'Pickles',
    shortDescription: 'Classic Andhra Avakaya. Tangy raw mangoes seasoned with heavy mustard powder and spicy Guntur chillies.',
    description: 'The undisputed king of pickles, our Avakaya is crafted using sour, firm green mangoes chopped into precise pieces. Each piece has the inner shell intact, ensuring a satisfying crunch. Marinated with pure mustard seed powder, fiery Guntur red chillies, and cold-pressed sesame oil, this pickle is aged to perfection to develop its robust, spicy profile.',
    spiceLevel: 'Extra Hot',
    bestWith: ['Curd Rice', 'Dosa', 'Plain Rice'],
    ingredients: ['Raw Green Mangoes', 'Cold-pressed Sesame Oil', 'Mustard Powder', 'Red Chilli Powder', 'Salt', 'Fenugreek Seeds', 'Turmeric'],
    storageInstructions: 'Store in a cool, dry place. Keep the jar tightly sealed. Use a dry spoon.',
    shelfLife: '9 Months',
    allergenWarning: 'Contains mustard. Prepared in a facility handling sesame and nuts.',
    imagePath: 'img/mango_pickle_packaging.jpg',
    secondaryImagePath: 'img/Gemini_Generated_Image_ (26).png',
    availabilityStatus: 'Preorder Interest Open'
  },
  {
    id: 'prawns-pickle',
    name: 'Prawns Pickle',
    category: 'Non-Veg Pickles',
    shortDescription: 'Authentic Andhra Style. Premium small-batch prawns pickle infused with traditional aromatic spices.',
    description: 'A true coastal Andhra delicacy, our premium Prawns Pickle (Royyala Avakaya) is crafted using fresh, succulent prawns cooked to a tender bite. Infused with cold-pressed sesame oil, Guntur red chillies, mustard powder, fenugreek, and hand-ground ginger-garlic paste. Perfectly spiced and aged to let the robust marine and spice flavors mature, it brings an irresistible savory richness.',
    spiceLevel: 'Hot',
    bestWith: ['Rice', 'Chapati', 'Dosa'],
    ingredients: ['Fresh Succulent Prawns', 'Cold-pressed Sesame Oil', 'Red Chilli Powder', 'Ginger-Garlic Paste', 'Salt', 'Mustard Seed Powder', 'Lemon Juice', 'Fenugreek Seeds', 'Turmeric'],
    storageInstructions: 'Store in a dry place. Keep the jar tightly sealed. Use a dry spoon.',
    shelfLife: '3 Months',
    allergenWarning: 'Contains shellfish (prawns) and garlic. Prepared in a facility handling sesame and nuts.',
    imagePath: 'img/prawns_pickle_packaging.jpg',
    availabilityStatus: 'Limited Batch'
  },
  {
    id: 'karampodi',
    name: 'Karampodi',
    category: 'Podis / Spice Powders',
    shortDescription: 'Stone-ground roasted lentils and hot red chillies, heavily infused with aromatic garlic.',
    description: 'Our signature garlic spice powder is stone-ground in small batches to preserve its rustic texture and natural oils. Prepared from select dried red chillies, roasted split lentils, and roasted cumin, all crushed together with fresh garlic cloves. It adds a powerful punch of heat and garlic aroma.',
    spiceLevel: 'Hot',
    bestWith: ['Idly + Ghee', 'Dosa', 'Upma'],
    ingredients: ['Dried Red Chillies', 'Garlic Cloves', 'Bengal Gram (Chana Dal)', 'Black Gram (Urad Dal)', 'Cumin Seeds', 'Salt', 'Sesame Seeds'],
    storageInstructions: 'Store in an airtight container in a dry place. Keep away from moisture.',
    shelfLife: '3 Months',
    allergenWarning: 'Contains sesame and garlic. Prepared in a kitchen handling nuts.',
    imagePath: 'img/Gemini_Generated_Image_ (14).png',
    availabilityStatus: 'Preorder Interest Open'
  },
  {
    id: 'idly-podi',
    name: 'Idly Podi / Puttanalu Podi',
    category: 'Podis / Spice Powders',
    shortDescription: 'Earthy roasted gram and coriander spice mix, a classic breakfast enhancer.',
    description: 'Our classic Idly Podi, also known as Puttanalu Podi in some regions, is crafted using roasted bengal gram (puttanalu), whole black gram, and a touch of tamarind for a light, sour finish. Spiced moderately, it has an earthy, savory base that comes alive when mixed with warm sesame oil or melted ghee over fresh idlis.',
    spiceLevel: 'Medium',
    bestWith: ['Soft Steamed Idlis', 'Dosa', 'Uttapam', 'Neyyi (Ghee) Rice'],
    ingredients: ['Roasted Bengal Gram', 'Black Gram (Urad Dal)', 'Red Chilli Powder', 'Coriander Seeds', 'Cumin', 'Tamarind', 'Salt'],
    storageInstructions: 'Store in an airtight jar. Protect from moisture.',
    shelfLife: '3 Months',
    allergenWarning: 'Prepared in a facility processing sesame and nuts.',
    imagePath: 'img/Gemini_Generated_Image_ (11).png',
    availabilityStatus: 'Preorder Interest Open'
  },
  {
    id: 'curry-leaf-podi',
    name: 'Curry Leaf Podi',
    category: 'Podis / Spice Powders',
    shortDescription: 'Premium International Edition. A highly aromatic, iron-rich spiced curry leaves powder.',
    description: 'Our Karivepaku Podi (Curry Leaf Powder) is a premium South Indian spiced condiment made from fresh, shade-dried curry leaves roasted to a crisp. Graded to Headmaster standards, it is stone-ground with roasted black gram (urad dal), bengal gram (chana dal), coriander seeds, cumin, and dry chillies.',
    spiceLevel: 'Medium',
    bestWith: ['Rice + Sesame Oil', 'Idly', 'Dosa', 'Upma'],
    ingredients: ['Fresh Curry Leaves', 'Black Gram (Urad Dal)', 'Bengal Gram (Chana Dal)', 'Coriander Seeds', 'Cumin Seeds', 'Dry Red Chillies', 'Salt'],
    storageInstructions: 'Store in an airtight container in a cool, dry, dark place.',
    shelfLife: '4 Months',
    allergenWarning: 'Contains sesame and pulses. Prepared in a facility handling nuts.',
    imagePath: 'img/curry_leaf_podi_packaging.jpg',
    secondaryImagePath: 'img/curry_leaf_podi_plating.jpg',
    availabilityStatus: 'Limited Batch'
  },
  {
    id: 'andhra-breakfast-combo',
    name: 'Andhra Breakfast Combo',
    category: 'Combo Boxes',
    shortDescription: 'A premium assortment of breakfast spices: Idly Podi, Karam Podi, and Curry Leaf Podi.',
    description: 'Make every breakfast feel like home. This combo packs three of our most popular spice powders (Idly Podi, Karam Podi, and Curry Leaf Podi) into custom storage-safe jars, designed to accompany idli, dosa, and upma.',
    spiceLevel: 'Medium',
    bestWith: ['Idly', 'Dosa', 'Upma'],
    ingredients: ['Roasted Lentils', 'Curry Leaves', 'Garlic', 'Chilli Powder', 'Sesame Oil', 'Salt'],
    storageInstructions: 'Keep in airtight containers, away from direct heat.',
    shelfLife: '4 Months',
    allergenWarning: 'Contains sesame, mustard, and garlic.',
    imagePath: 'img/Gemini_Generated_Image_ (2).png',
    availabilityStatus: 'Preorder Interest Open',
    isCombo: true,
    includedItems: ['Idly Podi', 'Karam Podi', 'Curry Leaf Podi']
  },
  {
    id: 'rice-lover-combo',
    name: 'Rice Lover Combo',
    category: 'Combo Boxes',
    shortDescription: 'The ultimate trio for hot rice enthusiasts: Gongura Pickle, Mango Pickle, and Karampodi.',
    description: 'Designed for the traditional hot rice + ghee experience. Includes our famous Gongura Pickle, classic Avakaya Mango Pickle, and the punchy garlic Karampodi. Mixed with a hot bowl of rice and melted ghee, this is Andhra comfort food at its finest.',
    spiceLevel: 'Extra Hot',
    bestWith: ['Hot Rice + Ghee', 'Curd Rice'],
    ingredients: ['Raw Mangoes', 'Sorrel Leaves', 'Garlic', 'Guntur Chilli', 'Sesame Oil', 'Spices'],
    storageInstructions: 'Store pickles in dry jars. Keep Karampodi in an airtight container.',
    shelfLife: '6 Months',
    allergenWarning: 'Contains mustard, sesame, garlic, and traces of nuts.',
    imagePath: 'img/Gemini_Generated_Image_ (26).png',
    availabilityStatus: 'Preorder Interest Open',
    isCombo: true,
    includedItems: ['Gongura Pickle', 'Mango Pickle', 'Karampodi']
  },
  {
    id: 'ammas-signature-box',
    name: 'Amma’s Signature Box',
    category: 'Combo Boxes',
    shortDescription: 'Amma’s ultimate curation: Mango Pickle, Gongura Pickle, Idly Podi, and Curry Leaf Podi.',
    description: 'The absolute best of Headmaster Amma’s kitchen. This collection features a curated combination of our top two pickles (Mango, Gongura) and top two podis (Idly Podi, Curry Leaf Podi). A complete taste profile covering tangy, fiery, savory, and aromatic flavors.',
    spiceLevel: 'Hot',
    bestWith: ['Rice', 'Idly', 'Dosa', 'Ghee'],
    ingredients: ['Raw Mangoes', 'Gongura Leaves', 'Curry Leaves', 'Roasted Lentils', 'Garlic', 'Spices'],
    storageInstructions: 'Follow individual jar instructions. Store in a dry place.',
    shelfLife: '6 Months',
    allergenWarning: 'Contains mustard, sesame, garlic, and pulses.',
    imagePath: 'img/Gemini_Generated_Image_ (16).png',
    availabilityStatus: 'Preorder Interest Open',
    isCombo: true,
    includedItems: ['Mango Pickle', 'Gongura Pickle', 'Idly Podi', 'Curry Leaf Podi']
  },
  {
    id: 'chicken-pickle',
    name: 'Chicken Pickle',
    category: 'Non-Veg Pickles',
    shortDescription: 'Spicy boneless chicken pickle slow-cooked with fresh ginger, garlic, and local spices.',
    description: 'A beloved Andhra non-veg specialty, chicken pieces are marinated in spices, cooked to tender, and combined with a thick spice gravy.',
    spiceLevel: 'Andhra Fire',
    bestWith: ['Hot Rice', 'Roti', 'Biryani'],
    ingredients: ['Boneless Chicken', 'Cold-pressed Oil', 'Ginger-Garlic Paste', 'Andhra Spices', 'Lemon Juice'],
    storageInstructions: 'Store in dry place. Keep the jar tightly sealed.',
    shelfLife: '2 Months',
    allergenWarning: 'Contains poultry and garlic. Prepared in a facility handling mustard and sesame.',
    imagePath: 'img/prawns_pickle_packaging.jpg',
    availabilityStatus: 'Coming Soon'
  },
  {
    id: 'mutton-pickle',
    name: 'Mutton Pickle',
    category: 'Non-Veg Pickles',
    shortDescription: 'Tender mutton chunks pickled in an aromatic, high-heat spice mix.',
    description: 'A premium delicacy. Hand-chopped tender mutton slow-cooked with traditional spices and Guntur red chillies.',
    spiceLevel: 'Andhra Fire',
    bestWith: ['Rice', 'Dosa', 'Parotta'],
    ingredients: ['Tender Mutton Chunks', 'Cold-pressed Oil', 'Ginger-Garlic Paste', 'Spices'],
    storageInstructions: 'Store in dry place. Keep the jar tightly sealed.',
    shelfLife: '2 Months',
    allergenWarning: 'Contains meat and garlic.',
    imagePath: 'img/prawns_pickle_packaging.jpg',
    availabilityStatus: 'Coming Soon'
  },
  {
    id: 'tomato-pickle',
    name: 'Tomato Pickle',
    category: 'Pickles',
    shortDescription: 'Sun-dried tomatoes cooked with tamarind, garlic, and hot red chillies.',
    description: 'A tangy, juicy, and spicy tomato pickle that brings the rich taste of traditional harvests to your table.',
    spiceLevel: 'Hot',
    bestWith: ['Idly', 'Dosa', 'Rice'],
    ingredients: ['Sun-dried Tomatoes', 'Tamarind', 'Garlic', 'Spices', 'Cold-pressed Oil'],
    storageInstructions: 'Store in a cool, dry place.',
    shelfLife: '6 Months',
    allergenWarning: 'Contains garlic and mustard.',
    imagePath: 'img/mango_pickle_packaging.jpg',
    availabilityStatus: 'Coming Soon'
  },
  {
    id: 'garlic-pickle',
    name: 'Garlic Pickle',
    category: 'Pickles',
    shortDescription: 'Whole peeled garlic cloves pickled in a heavy mustard-chilli oil.',
    description: 'For garlic lovers. Whole cloves are pickled to a soft, flavorful texture in a spicy mustard oil base.',
    spiceLevel: 'Hot',
    bestWith: ['Rice', 'Roti', 'Curd Rice'],
    ingredients: ['Garlic Cloves', 'Mustard Oil', 'Chilli Powder', 'Spices'],
    storageInstructions: 'Store in a cool, dry place. Keep sealed.',
    shelfLife: '6 Months',
    allergenWarning: 'Contains garlic and mustard.',
    imagePath: 'img/mango_pickle_packaging.jpg',
    availabilityStatus: 'Coming Soon'
  },
  {
    id: 'green-chilli-pickle',
    name: 'Green Chilli Pickle',
    category: 'Pickles',
    shortDescription: 'Fiery slit green chillies salted and spiced with mustard seeds and lemon.',
    description: 'A pungent and sharp pickle made from high-heat local green chillies, slit and seasoned to perfection.',
    spiceLevel: 'Andhra Fire',
    bestWith: ['Curd Rice', 'Roti', 'Mathri'],
    ingredients: ['Green Chillies', 'Lemon Juice', 'Mustard Seed Powder', 'Salt', 'Spices'],
    storageInstructions: 'Store in a cool, dry place.',
    shelfLife: '4 Months',
    allergenWarning: 'Contains mustard.',
    imagePath: 'img/gongura_pickle_packaging.jpg',
    availabilityStatus: 'Coming Soon'
  },
  {
    id: 'nuvvula-podi',
    name: 'Nuvvula Podi',
    category: 'Podis / Spice Powders',
    shortDescription: 'Toasted sesame seeds ground with roasted red chillies and garlic.',
    description: 'Sesame seed spice powder. A highly nutritious, aromatic condiment that adds a rich nutty warmth.',
    spiceLevel: 'Medium',
    bestWith: ['Steamed Rice + Ghee', 'Dosa'],
    ingredients: ['Sesame Seeds', 'Dry Red Chillies', 'Garlic', 'Cumin', 'Salt'],
    storageInstructions: 'Store in airtight container. Keep dry.',
    shelfLife: '3 Months',
    allergenWarning: 'Contains sesame and garlic.',
    imagePath: 'img/Gemini_Generated_Image_ (11).png',
    availabilityStatus: 'Coming Soon'
  },
  {
    id: 'groundnut-podi',
    name: 'Groundnut Podi',
    category: 'Podis / Spice Powders',
    shortDescription: 'Roasted peanuts stone-ground with garlic, cumin, and dry chillies.',
    description: 'A crunchy, savory peanut spice powder that pairs beautifully with breakfast items or plain rice.',
    spiceLevel: 'Medium',
    bestWith: ['Idly', 'Dosa', 'Rice'],
    ingredients: ['Peanuts (Groundnuts)', 'Dry Red Chillies', 'Garlic', 'Cumin', 'Salt'],
    storageInstructions: 'Store in airtight jar. Protect from moisture.',
    shelfLife: '3 Months',
    allergenWarning: 'Contains peanuts (groundnuts) and garlic.',
    imagePath: 'img/Gemini_Generated_Image_ (14).png',
    availabilityStatus: 'Coming Soon'
  }
];
